In [1]:
# Import necessary libraries for TensorFlow and NumPy.
import tensorflow as tf
import numpy as np

In [2]:
# Define input features (X) and target labels (y) for an AND gate.
X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
], dtype=np.float32)

y = np.array([
    [0],
    [0],
    [0],
    [1]
], dtype=np.float32)


print(X)
print(y)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
[[0.]
 [0.]
 [0.]
 [1.]]


In [3]:
# Define a simple sequential Keras model with a single dense layer and sigmoid activation for binary classification.
model = tf.keras.Sequential([
    tf.keras.layers.Dense(
        units=1,
        activation='sigmoid',
        input_shape=(2,)
    )
])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
# Compile the model using SGD optimizer and binary cross-entropy loss.
model.compile(
    optimizer='sgd',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [5]:
# Train the model on the defined dataset for 500 epochs.
model.fit(
    X,
    y,
    epochs=500,
    verbose=1
)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 512ms/step - accuracy: 0.7500 - loss: 0.7857
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.7840
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.7500 - loss: 0.7823
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.7806
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.7500 - loss: 0.7789
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7500 - loss: 0.7773
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7500 - loss: 0.7756
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7500 - loss: 0.7740
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7500 - loss: 0.7723
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7500 - loss: 0.7707
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.7500 - loss: 0.7691
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7500 - l

In [6]:
# Make predictions on the input data using the trained model.
prediction = model.predict(X)

print("Predicted Values")

for i in range(len(X)):
    print(X[i], "->", prediction[i][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step
Predicted Values
[0. 0.] -> 0.25142527
[0. 1.] -> 0.48857564
[1. 0.] -> 0.25495
[1. 1.] -> 0.49323434


In [7]:
# Convert the probabilistic predictions into binary outputs (0 or 1) using a 0.5 threshold.
binary_output = (prediction > 0.5).astype(int)

print(binary_output)

[[0]
 [0]
 [0]
 [0]]


In [8]:
# Retrieve and display the learned weights and bias of the model's dense layer.
weights, bias = model.layers[0].get_weights()

print("Weights")

print(weights)

print("\nBias")

print(bias)

Weights
[[0.01864126]
 [1.0453198 ]]

Bias
[-1.0910252]


In [9]:
#model summary
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5 (24.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)